services: 
    neovim:
        build: ./
        container_name: neovim
        tty: true
        environment:
          TZ: Asia/Tokyo
          XDG_CACHE_HOME: /root/.cache
        volumes:
          # プロジェクトディレクトリの同期
          - $HOME:$HOME
          # nvimの設定を弄った時のために同期しておく
          - ./config/nvim:/root/.config/nvim 
          # LSPなどmasonでインストールするものは立ち上げるたびにインストールされるのでここで永続化
          - mason_data:/root/.local/share/nvim/mason 
          # nvimやLSPのキャッシュ 立ち上げるたびにindex作り直すので永続化
          - nvim_cache:/root/.cache 
          # treesitterのパーサー 立ち上げる度に消えるので永続化
          - treesitter_parser:/root/.local/share/nvim/lazy/nvim-treesitter/parser

volumes:
  mason_data:
  nvim_cache:
  treesitter_parser:
